import Head from 'next/head';
import { Button, Card, CardContent, CardHeader, Link, Stack, TextField, Typography } from '@mui/material';
import Spacer from 'react-spacer';
import { useState } from 'react';
import axios, { AxiosError } from 'axios';
import { Web3Button, useWeb3Modal } from '@web3modal/react';
import { useAccount, useSignMessage } from 'wagmi';
// @ts-ignore
import NoSSR from 'react-no-ssr';

export default function Home() {

  const [name, setName] = useState('');
  const [familyName, setFamilyName] = useState('');
  const { open, close } = useWeb3Modal();
  const [success, setSuccess] = useState(false);
  const account = useAccount();
  const { signMessageAsync } = useSignMessage();
  const [qrCode, setQrCode] = useState('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=');

  const getIdentity = async (e: any) => {

    try {
      const message = account.address + process.env.NEXT_PUBLIC_PROJECT_NAME!;
      const signature = await signMessageAsync({
        message
      });
      const { data } = await axios.post(`${process.env.NEXT_PUBLIC_HOST}/api/register`, {
        name,
        surname: familyName,
        address: account.address,
        signature
      });
      setSuccess(true);
      // setQrCode(data.qrCode);
      localStorage.setItem('identity', data.jwt);
    } catch (err: any) {
      const axiosError = err as AxiosError;
      console.log(err);
      alert((axiosError.response?.data as any)?.error ?? 'Internal Server Error');
    }
  }

  return (
    <>
      <Head>
        <title>Identity Provider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack alignItems='center'>
        <img src='/logo.png' width='30%' height='30%' style={{ marginTop: '5vh' }} />
        <Stack direction='row' justifyContent='center' alignItems='center' marginTop='5vh' spacing='2vw' height='60vh'>
          <Card sx={{ height: '100%', width: '30vw' }}>
            {
              success ? <CardHeader title='NFT Rilasciato' sx={{ textAlign: 'center' }} /> : null
            }
            <CardContent sx={{ marginLeft: '5%', marginRight: '5%', height: '100%' }}>
              <Stack spacing='2vh' justifyContent='center' height='100%'>
                {
                  
                  success ? <Stack alignItems='center'><Typography>Credenziale registrata su Blockchain e credenziale verificabile creata!</Typography><img src={qrCode} style={{width: '40vh', height: '40vh'}}/></Stack> : <>
                    <Spacer grow={1} />
                    <TextField onChange={(e) => { setName(e.target.value) }} label='Nome'></TextField>
                    <TextField onChange={(e) => { setFamilyName(e.target.value) }} label='Cognome'></TextField>
                    <NoSSR>
                      {
                        account.isConnected ? <Button onClick={getIdentity}>Crea</Button> : <Button onClick={() => open()}>Connetti Wallet</Button>
                      }
                    </NoSSR>
                  </>
                }
                <Spacer grow={2} />
              </Stack>
            </CardContent>
          </Card>
        </Stack>
      </Stack>
    </>
  )
}

