import Head from 'next/head';
import { Button, Card, CardContent, CardHeader, Link, Stack, TextField, Typography } from '@mui/material';
import Spacer from 'react-spacer';
import { useEffect, useState } from 'react';
import axios, { AxiosError } from 'axios';
import { Web3Button, useWeb3Modal } from '@web3modal/react';
import { useAccount, useSignMessage } from 'wagmi';
import { useRouter } from 'next/router'
// @ts-ignore
import NoSSR from 'react-no-ssr';

export default function Verify() {

    const router = useRouter()
    const { URL, name } = router.query;
    const [url, setUrl] = useState('');

    useEffect(() => {
        if (URL != null) {
            setUrl(Buffer.from(URL as string, 'base64').toString('ascii'));
        }
    }, [URL])
    return (
        <>
            <Head>
                <title>Identity Provider</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Stack alignItems='center' spacing={2} marginTop='1'>
                <Typography>Vuoi condividere la tua credenziale con {name}?</Typography>
                <Button variant='contained' onClick={async () => {
                    await axios.post(url, {
                        jwt: localStorage.getItem('identity')
                    })
                    alert("Credenziale inviata!");
                    window.close();
                }}>Condividi</Button>
            </Stack>
        </>
    )
}

